---

- etckeeper: action=begin


- name: Install package
  apt: name=unattended-upgrades state=present

- name: Configure unattended-upgrades
  copy: src=unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades force=yes


- etckeeper: "action=commit msg='ansible: {{ vars['role_name'] }}.unattended-upgrades' rev={{ revision }}"
