---

- etckeeper: action=begin


- name: Create user for {{ username }}
  user:
    name: "{{ username }}"
    home: "{{ userhome }}"
    groups: "{{ usergroups | default('') }}"
    shell: /usr/bin/zsh
    update_password: on_create


- etckeeper: "action=commit msg='ansible: {{ vars['role_name'] }}.create-user' rev={{ revision }}"
