---

- name: Deploy SSH keys for {{ username }}
  authorized_key: key="{{ item }}" user="{{ username }}"
  with_items: "{{ user_pubkeys[username] }}"
  when: ansible_connection is undefined or ansible_connection != "local" # don't deploy on local runs
